/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 [prototype]mall_groundfloor.glb storefront_mr-chocolate.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Mall_Groundfloor(props) {

  //the layout rendered will be based on the .length of the searchResults


  const { nodes, materials } = useGLTF('/models/[prototype]mall_groundfloor.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mall_storefront_plot.geometry} material={materials.Mall_storefront_plot} position={[0, 0.001, 0]} />
      <mesh geometry={nodes.mall_storefront_plot_spacer.geometry} material={materials.Mall_storefront_plot_spacer} scale={[1, 0, 1]} />
    </group>
  )
}

useGLTF.preload('/models/[prototype]mall_groundfloor.glb')
