/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 mall_layout1.gltf 
*/

import React from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/mall_layout1.gltf')
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={22.895} position={[8.765, 1.647, 7.462]} rotation={[-0.018, 0.874, 0.014]} />
      <mesh geometry={nodes.mall_storefront_plot.geometry} material={materials.Mall_storefront_plot} position={[0, 0.001, 0]} />
      <mesh geometry={nodes.mall_storefront_plot_spacer.geometry} material={materials.Mall_storefront_plot_spacer} scale={[1, 0, 1]} />
    </group>
  )
}

useGLTF.preload('/mall_layout1.gltf')
