"use client"
import "./globals.css";
import UIGrid from "./sections/UIGrid/UIGrid";
import { useEffect, useState } from "react";
import {CameraProvider} from "./Providers/CameraProvider";
import {EntryDoorsProvider} from "./Providers/EntryDoorsProvider";
import { StorefrontProvider } from "./Providers/StorefrontProvider";
import { UserInfoProvider } from "./Providers/UserInfoProvider";
import styles from "./sections/styles.module.scss";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };



export default function RootLayout({ children }) {
  const [mainSectionHeight, setMainSectionHeight] = useState(0);
  const [headerFooterHeight,setHeaderFooterHeight] = useState(90);

  useEffect(() =>{
    const headerHeight = getComputedStyle(document.documentElement)
    .getPropertyValue("--headerFooterHeight")
    setHeaderFooterHeight(headerHeight);
  },[]);

  useEffect(() => {
    const updateHeight = () => {
      const height = window.innerHeight - (headerFooterHeight * 2);
      setMainSectionHeight(height);
    };

    updateHeight(); // Set initial height
    window.addEventListener('resize', updateHeight); // Update height on window resize

    return () => {
      window.removeEventListener('resize', updateHeight); // Cleanup listener on unmount
    };
  }, []);

  return (
    <html lang="en">
      <body >
        <UserInfoProvider>
          <CameraProvider>
          <EntryDoorsProvider>
            <StorefrontProvider>
              <UIGrid height={headerFooterHeight}>
                <main style={{ height: mainSectionHeight + "px" }} className={styles.main}>
                  {children}
                </main>
              </UIGrid>
            </StorefrontProvider>
            </EntryDoorsProvider>
          </CameraProvider>
        </UserInfoProvider>
      </body>

    </html>
  );
}
