"use client"
import "./globals.css";
import Header from "./sections/Header/Header";
import Footer from "./sections/Footer/Footer";
import { useEffect } from "react";



// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const headerFooterHeight = 70;

export default function RootLayout({ children }) {

  const mainSectionHeight = window.innerHeight - (headerFooterHeight * 2) ;

  return (
    <html lang="en">
      <body >
        <Header height={headerFooterHeight}/>
        <main  style={{height:mainSectionHeight  + "px"}}  className="w-full  bg-slate-800 flex justify-center items-center ">
          {children}
        </main>
        <Footer height={headerFooterHeight}/>
      </body>
    </html>
  );
}
